version: '3'

services:
  chat2api:
    image: h88782481/chat-share:latest
    container_name: chat-share
    restart: unless-stopped
    ports:
      - '5100:5100'
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
      - SECRET_KEY=your_admin_secret_key
      - AUTHORIZATION=your_authorization
      - DOMAIN_CHATGPT=http://127.0.0.1:5005

